// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.server.bean;

public final class ClientInformationPacket {
  private ClientInformationPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientProcOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ClientProc.CUser user = 1;
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    com.server.bean.ClientInformationPacket.ClientProc.CUser getUser();
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder getUserOrBuilder();

    // optional .ClientProc.CChatInfo chatInfo = 2;
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    boolean hasChatInfo();
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    com.server.bean.ClientInformationPacket.ClientProc.CChatInfo getChatInfo();
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder getChatInfoOrBuilder();
  }
  /**
   * Protobuf type {@code ClientProc}
   */
  public static final class ClientProc extends
      com.google.protobuf.GeneratedMessage
      implements ClientProcOrBuilder {
    // Use ClientProc.newBuilder() to construct.
    private ClientProc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientProc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientProc defaultInstance;
    public static ClientProc getDefaultInstance() {
      return defaultInstance;
    }

    public ClientProc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientProc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.server.bean.ClientInformationPacket.ClientProc.CUser.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = chatInfo_.toBuilder();
              }
              chatInfo_ = input.readMessage(com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatInfo_);
                chatInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.bean.ClientInformationPacket.internal_static_ClientProc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.bean.ClientInformationPacket.internal_static_ClientProc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.bean.ClientInformationPacket.ClientProc.class, com.server.bean.ClientInformationPacket.ClientProc.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientProc> PARSER =
        new com.google.protobuf.AbstractParser<ClientProc>() {
      public ClientProc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientProc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientProc> getParserForType() {
      return PARSER;
    }

    public interface CUserOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string id = 1;
      /**
       * <code>required string id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>required string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      // required string userName = 2;
      /**
       * <code>required string userName = 2;</code>
       */
      boolean hasUserName();
      /**
       * <code>required string userName = 2;</code>
       */
      java.lang.String getUserName();
      /**
       * <code>required string userName = 2;</code>
       */
      com.google.protobuf.ByteString
          getUserNameBytes();

      // required string userPwd = 3;
      /**
       * <code>required string userPwd = 3;</code>
       */
      boolean hasUserPwd();
      /**
       * <code>required string userPwd = 3;</code>
       */
      java.lang.String getUserPwd();
      /**
       * <code>required string userPwd = 3;</code>
       */
      com.google.protobuf.ByteString
          getUserPwdBytes();
    }
    /**
     * Protobuf type {@code ClientProc.CUser}
     */
    public static final class CUser extends
        com.google.protobuf.GeneratedMessage
        implements CUserOrBuilder {
      // Use CUser.newBuilder() to construct.
      private CUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CUser defaultInstance;
      public static CUser getDefaultInstance() {
        return defaultInstance;
      }

      public CUser getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CUser(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                id_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                userName_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                userPwd_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ClientInformationPacket.ClientProc.CUser.class, com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder.class);
      }

      public static com.google.protobuf.Parser<CUser> PARSER =
          new com.google.protobuf.AbstractParser<CUser>() {
        public CUser parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUser(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CUser> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private java.lang.Object id_;
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string userName = 2;
      public static final int USERNAME_FIELD_NUMBER = 2;
      private java.lang.Object userName_;
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string userPwd = 3;
      public static final int USERPWD_FIELD_NUMBER = 3;
      private java.lang.Object userPwd_;
      /**
       * <code>required string userPwd = 3;</code>
       */
      public boolean hasUserPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userPwd = 3;</code>
       */
      public java.lang.String getUserPwd() {
        java.lang.Object ref = userPwd_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userPwd_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string userPwd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPwdBytes() {
        java.lang.Object ref = userPwd_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        id_ = "";
        userName_ = "";
        userPwd_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUserName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUserPwd()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getUserNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getUserPwdBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getUserNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getUserPwdBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CUser parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.bean.ClientInformationPacket.ClientProc.CUser prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ClientProc.CUser}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CUser_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CUser_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.bean.ClientInformationPacket.ClientProc.CUser.class, com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder.class);
        }

        // Construct using com.server.bean.ClientInformationPacket.ClientProc.CUser.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          userName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          userPwd_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CUser_descriptor;
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CUser getDefaultInstanceForType() {
          return com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance();
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CUser build() {
          com.server.bean.ClientInformationPacket.ClientProc.CUser result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CUser buildPartial() {
          com.server.bean.ClientInformationPacket.ClientProc.CUser result = new com.server.bean.ClientInformationPacket.ClientProc.CUser(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.userName_ = userName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.userPwd_ = userPwd_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.bean.ClientInformationPacket.ClientProc.CUser) {
            return mergeFrom((com.server.bean.ClientInformationPacket.ClientProc.CUser)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.bean.ClientInformationPacket.ClientProc.CUser other) {
          if (other == com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance()) return this;
          if (other.hasId()) {
            bitField0_ |= 0x00000001;
            id_ = other.id_;
            onChanged();
          }
          if (other.hasUserName()) {
            bitField0_ |= 0x00000002;
            userName_ = other.userName_;
            onChanged();
          }
          if (other.hasUserPwd()) {
            bitField0_ |= 0x00000004;
            userPwd_ = other.userPwd_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasUserName()) {
            
            return false;
          }
          if (!hasUserPwd()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.bean.ClientInformationPacket.ClientProc.CUser parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.bean.ClientInformationPacket.ClientProc.CUser) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string id = 1;
        private java.lang.Object id_ = "";
        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }

        // required string userName = 2;
        private java.lang.Object userName_ = "";
        /**
         * <code>required string userName = 2;</code>
         */
        public boolean hasUserName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string userName = 2;</code>
         */
        public java.lang.String getUserName() {
          java.lang.Object ref = userName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            userName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string userName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUserNameBytes() {
          java.lang.Object ref = userName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string userName = 2;</code>
         */
        public Builder setUserName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          userName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string userName = 2;</code>
         */
        public Builder clearUserName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          userName_ = getDefaultInstance().getUserName();
          onChanged();
          return this;
        }
        /**
         * <code>required string userName = 2;</code>
         */
        public Builder setUserNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          userName_ = value;
          onChanged();
          return this;
        }

        // required string userPwd = 3;
        private java.lang.Object userPwd_ = "";
        /**
         * <code>required string userPwd = 3;</code>
         */
        public boolean hasUserPwd() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string userPwd = 3;</code>
         */
        public java.lang.String getUserPwd() {
          java.lang.Object ref = userPwd_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            userPwd_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string userPwd = 3;</code>
         */
        public com.google.protobuf.ByteString
            getUserPwdBytes() {
          java.lang.Object ref = userPwd_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userPwd_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string userPwd = 3;</code>
         */
        public Builder setUserPwd(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          userPwd_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string userPwd = 3;</code>
         */
        public Builder clearUserPwd() {
          bitField0_ = (bitField0_ & ~0x00000004);
          userPwd_ = getDefaultInstance().getUserPwd();
          onChanged();
          return this;
        }
        /**
         * <code>required string userPwd = 3;</code>
         */
        public Builder setUserPwdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          userPwd_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ClientProc.CUser)
      }

      static {
        defaultInstance = new CUser(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ClientProc.CUser)
    }

    public interface CChatInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string type = 1;
      /**
       * <code>required string type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 1;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 1;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      // required string words = 2;
      /**
       * <code>required string words = 2;</code>
       */
      boolean hasWords();
      /**
       * <code>required string words = 2;</code>
       */
      java.lang.String getWords();
      /**
       * <code>required string words = 2;</code>
       */
      com.google.protobuf.ByteString
          getWordsBytes();
    }
    /**
     * Protobuf type {@code ClientProc.CChatInfo}
     */
    public static final class CChatInfo extends
        com.google.protobuf.GeneratedMessage
        implements CChatInfoOrBuilder {
      // Use CChatInfo.newBuilder() to construct.
      private CChatInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CChatInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CChatInfo defaultInstance;
      public static CChatInfo getDefaultInstance() {
        return defaultInstance;
      }

      public CChatInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CChatInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                type_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                words_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CChatInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CChatInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.class, com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<CChatInfo> PARSER =
          new com.google.protobuf.AbstractParser<CChatInfo>() {
        public CChatInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CChatInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CChatInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private java.lang.Object type_;
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string words = 2;
      public static final int WORDS_FIELD_NUMBER = 2;
      private java.lang.Object words_;
      /**
       * <code>required string words = 2;</code>
       */
      public boolean hasWords() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string words = 2;</code>
       */
      public java.lang.String getWords() {
        java.lang.Object ref = words_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            words_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string words = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWordsBytes() {
        java.lang.Object ref = words_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          words_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = "";
        words_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWords()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getWordsBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getWordsBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.bean.ClientInformationPacket.ClientProc.CChatInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ClientProc.CChatInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CChatInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CChatInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.class, com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder.class);
        }

        // Construct using com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          words_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.bean.ClientInformationPacket.internal_static_ClientProc_CChatInfo_descriptor;
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo getDefaultInstanceForType() {
          return com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance();
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo build() {
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo buildPartial() {
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo result = new com.server.bean.ClientInformationPacket.ClientProc.CChatInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.words_ = words_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.bean.ClientInformationPacket.ClientProc.CChatInfo) {
            return mergeFrom((com.server.bean.ClientInformationPacket.ClientProc.CChatInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.bean.ClientInformationPacket.ClientProc.CChatInfo other) {
          if (other == com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance()) return this;
          if (other.hasType()) {
            bitField0_ |= 0x00000001;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasWords()) {
            bitField0_ |= 0x00000002;
            words_ = other.words_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasWords()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.bean.ClientInformationPacket.ClientProc.CChatInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string type = 1;
        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string type = 1;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }

        // required string words = 2;
        private java.lang.Object words_ = "";
        /**
         * <code>required string words = 2;</code>
         */
        public boolean hasWords() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string words = 2;</code>
         */
        public java.lang.String getWords() {
          java.lang.Object ref = words_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            words_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string words = 2;</code>
         */
        public com.google.protobuf.ByteString
            getWordsBytes() {
          java.lang.Object ref = words_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            words_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string words = 2;</code>
         */
        public Builder setWords(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          words_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string words = 2;</code>
         */
        public Builder clearWords() {
          bitField0_ = (bitField0_ & ~0x00000002);
          words_ = getDefaultInstance().getWords();
          onChanged();
          return this;
        }
        /**
         * <code>required string words = 2;</code>
         */
        public Builder setWordsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          words_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ClientProc.CChatInfo)
      }

      static {
        defaultInstance = new CChatInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ClientProc.CChatInfo)
    }

    private int bitField0_;
    // optional .ClientProc.CUser user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private com.server.bean.ClientInformationPacket.ClientProc.CUser user_;
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    public com.server.bean.ClientInformationPacket.ClientProc.CUser getUser() {
      return user_;
    }
    /**
     * <code>optional .ClientProc.CUser user = 1;</code>
     */
    public com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder getUserOrBuilder() {
      return user_;
    }

    // optional .ClientProc.CChatInfo chatInfo = 2;
    public static final int CHATINFO_FIELD_NUMBER = 2;
    private com.server.bean.ClientInformationPacket.ClientProc.CChatInfo chatInfo_;
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    public boolean hasChatInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo getChatInfo() {
      return chatInfo_;
    }
    /**
     * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
     */
    public com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder getChatInfoOrBuilder() {
      return chatInfo_;
    }

    private void initFields() {
      user_ = com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance();
      chatInfo_ = com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasUser()) {
        if (!getUser().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasChatInfo()) {
        if (!getChatInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, chatInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chatInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.bean.ClientInformationPacket.ClientProc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.bean.ClientInformationPacket.ClientProc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientProc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.bean.ClientInformationPacket.ClientProcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ClientInformationPacket.ClientProc.class, com.server.bean.ClientInformationPacket.ClientProc.Builder.class);
      }

      // Construct using com.server.bean.ClientInformationPacket.ClientProc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
          getChatInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chatInfoBuilder_ == null) {
          chatInfo_ = com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance();
        } else {
          chatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.bean.ClientInformationPacket.internal_static_ClientProc_descriptor;
      }

      public com.server.bean.ClientInformationPacket.ClientProc getDefaultInstanceForType() {
        return com.server.bean.ClientInformationPacket.ClientProc.getDefaultInstance();
      }

      public com.server.bean.ClientInformationPacket.ClientProc build() {
        com.server.bean.ClientInformationPacket.ClientProc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.bean.ClientInformationPacket.ClientProc buildPartial() {
        com.server.bean.ClientInformationPacket.ClientProc result = new com.server.bean.ClientInformationPacket.ClientProc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (chatInfoBuilder_ == null) {
          result.chatInfo_ = chatInfo_;
        } else {
          result.chatInfo_ = chatInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.bean.ClientInformationPacket.ClientProc) {
          return mergeFrom((com.server.bean.ClientInformationPacket.ClientProc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.bean.ClientInformationPacket.ClientProc other) {
        if (other == com.server.bean.ClientInformationPacket.ClientProc.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasChatInfo()) {
          mergeChatInfo(other.getChatInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasUser()) {
          if (!getUser().isInitialized()) {
            
            return false;
          }
        }
        if (hasChatInfo()) {
          if (!getChatInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.bean.ClientInformationPacket.ClientProc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.bean.ClientInformationPacket.ClientProc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ClientProc.CUser user = 1;
      private com.server.bean.ClientInformationPacket.ClientProc.CUser user_ = com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ClientInformationPacket.ClientProc.CUser, com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder, com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder> userBuilder_;
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CUser getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public Builder setUser(com.server.bean.ClientInformationPacket.ClientProc.CUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public Builder setUser(
          com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public Builder mergeUser(com.server.bean.ClientInformationPacket.ClientProc.CUser value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              user_ != com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance()) {
            user_ =
              com.server.bean.ClientInformationPacket.ClientProc.CUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.server.bean.ClientInformationPacket.ClientProc.CUser.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder getUserBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      /**
       * <code>optional .ClientProc.CUser user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ClientInformationPacket.ClientProc.CUser, com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder, com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.bean.ClientInformationPacket.ClientProc.CUser, com.server.bean.ClientInformationPacket.ClientProc.CUser.Builder, com.server.bean.ClientInformationPacket.ClientProc.CUserOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // optional .ClientProc.CChatInfo chatInfo = 2;
      private com.server.bean.ClientInformationPacket.ClientProc.CChatInfo chatInfo_ = com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo, com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder, com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder> chatInfoBuilder_;
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public boolean hasChatInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo getChatInfo() {
        if (chatInfoBuilder_ == null) {
          return chatInfo_;
        } else {
          return chatInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public Builder setChatInfo(com.server.bean.ClientInformationPacket.ClientProc.CChatInfo value) {
        if (chatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatInfo_ = value;
          onChanged();
        } else {
          chatInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public Builder setChatInfo(
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder builderForValue) {
        if (chatInfoBuilder_ == null) {
          chatInfo_ = builderForValue.build();
          onChanged();
        } else {
          chatInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public Builder mergeChatInfo(com.server.bean.ClientInformationPacket.ClientProc.CChatInfo value) {
        if (chatInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              chatInfo_ != com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance()) {
            chatInfo_ =
              com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.newBuilder(chatInfo_).mergeFrom(value).buildPartial();
          } else {
            chatInfo_ = value;
          }
          onChanged();
        } else {
          chatInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public Builder clearChatInfo() {
        if (chatInfoBuilder_ == null) {
          chatInfo_ = com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.getDefaultInstance();
          onChanged();
        } else {
          chatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder getChatInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getChatInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder getChatInfoOrBuilder() {
        if (chatInfoBuilder_ != null) {
          return chatInfoBuilder_.getMessageOrBuilder();
        } else {
          return chatInfo_;
        }
      }
      /**
       * <code>optional .ClientProc.CChatInfo chatInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ClientInformationPacket.ClientProc.CChatInfo, com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder, com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder> 
          getChatInfoFieldBuilder() {
        if (chatInfoBuilder_ == null) {
          chatInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.bean.ClientInformationPacket.ClientProc.CChatInfo, com.server.bean.ClientInformationPacket.ClientProc.CChatInfo.Builder, com.server.bean.ClientInformationPacket.ClientProc.CChatInfoOrBuilder>(
                  chatInfo_,
                  getParentForChildren(),
                  isClean());
          chatInfo_ = null;
        }
        return chatInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClientProc)
    }

    static {
      defaultInstance = new ClientProc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientProc)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientProc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientProc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientProc_CUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientProc_CUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientProc_CChatInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientProc_CChatInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\"\270\001\n\nClientProc\022\037\n\004user\030\001 " +
      "\001(\0132\021.ClientProc.CUser\022\'\n\010chatInfo\030\002 \001(\013" +
      "2\025.ClientProc.CChatInfo\0326\n\005CUser\022\n\n\002id\030\001" +
      " \002(\t\022\020\n\010userName\030\002 \002(\t\022\017\n\007userPwd\030\003 \002(\t\032" +
      "(\n\tCChatInfo\022\014\n\004type\030\001 \002(\t\022\r\n\005words\030\002 \002(" +
      "\tB*\n\017com.server.beanB\027ClientInformationP" +
      "acket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClientProc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClientProc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClientProc_descriptor,
              new java.lang.String[] { "User", "ChatInfo", });
          internal_static_ClientProc_CUser_descriptor =
            internal_static_ClientProc_descriptor.getNestedTypes().get(0);
          internal_static_ClientProc_CUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClientProc_CUser_descriptor,
              new java.lang.String[] { "Id", "UserName", "UserPwd", });
          internal_static_ClientProc_CChatInfo_descriptor =
            internal_static_ClientProc_descriptor.getNestedTypes().get(1);
          internal_static_ClientProc_CChatInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClientProc_CChatInfo_descriptor,
              new java.lang.String[] { "Type", "Words", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
