// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.server.bean;

public final class ServerInformationPacket {
  private ServerInformationPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerProcOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ServerProc.SUser user = 1;
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    com.server.bean.ServerInformationPacket.ServerProc.SUser getUser();
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder getUserOrBuilder();

    // optional .ServerProc.SChatInfo chatInfo = 2;
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    boolean hasChatInfo();
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    com.server.bean.ServerInformationPacket.ServerProc.SChatInfo getChatInfo();
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder getChatInfoOrBuilder();
  }
  /**
   * Protobuf type {@code ServerProc}
   */
  public static final class ServerProc extends
      com.google.protobuf.GeneratedMessage
      implements ServerProcOrBuilder {
    // Use ServerProc.newBuilder() to construct.
    private ServerProc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerProc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerProc defaultInstance;
    public static ServerProc getDefaultInstance() {
      return defaultInstance;
    }

    public ServerProc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerProc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.server.bean.ServerInformationPacket.ServerProc.SUser.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = chatInfo_.toBuilder();
              }
              chatInfo_ = input.readMessage(com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatInfo_);
                chatInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.bean.ServerInformationPacket.internal_static_ServerProc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.bean.ServerInformationPacket.internal_static_ServerProc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.bean.ServerInformationPacket.ServerProc.class, com.server.bean.ServerInformationPacket.ServerProc.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerProc> PARSER =
        new com.google.protobuf.AbstractParser<ServerProc>() {
      public ServerProc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerProc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerProc> getParserForType() {
      return PARSER;
    }

    public interface SUserOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string result = 1;
      /**
       * <code>required string result = 1;</code>
       */
      boolean hasResult();
      /**
       * <code>required string result = 1;</code>
       */
      java.lang.String getResult();
      /**
       * <code>required string result = 1;</code>
       */
      com.google.protobuf.ByteString
          getResultBytes();
    }
    /**
     * Protobuf type {@code ServerProc.SUser}
     */
    public static final class SUser extends
        com.google.protobuf.GeneratedMessage
        implements SUserOrBuilder {
      // Use SUser.newBuilder() to construct.
      private SUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SUser defaultInstance;
      public static SUser getDefaultInstance() {
        return defaultInstance;
      }

      public SUser getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SUser(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                result_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ServerInformationPacket.ServerProc.SUser.class, com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder.class);
      }

      public static com.google.protobuf.Parser<SUser> PARSER =
          new com.google.protobuf.AbstractParser<SUser>() {
        public SUser parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SUser(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SUser> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string result = 1;
      public static final int RESULT_FIELD_NUMBER = 1;
      private java.lang.Object result_;
      /**
       * <code>required string result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        result_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasResult()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getResultBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getResultBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SUser parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.bean.ServerInformationPacket.ServerProc.SUser prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ServerProc.SUser}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SUser_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SUser_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.bean.ServerInformationPacket.ServerProc.SUser.class, com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder.class);
        }

        // Construct using com.server.bean.ServerInformationPacket.ServerProc.SUser.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          result_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SUser_descriptor;
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SUser getDefaultInstanceForType() {
          return com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance();
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SUser build() {
          com.server.bean.ServerInformationPacket.ServerProc.SUser result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SUser buildPartial() {
          com.server.bean.ServerInformationPacket.ServerProc.SUser result = new com.server.bean.ServerInformationPacket.ServerProc.SUser(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.result_ = result_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.bean.ServerInformationPacket.ServerProc.SUser) {
            return mergeFrom((com.server.bean.ServerInformationPacket.ServerProc.SUser)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.bean.ServerInformationPacket.ServerProc.SUser other) {
          if (other == com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance()) return this;
          if (other.hasResult()) {
            bitField0_ |= 0x00000001;
            result_ = other.result_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResult()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.bean.ServerInformationPacket.ServerProc.SUser parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.bean.ServerInformationPacket.ServerProc.SUser) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string result = 1;
        private java.lang.Object result_ = "";
        /**
         * <code>required string result = 1;</code>
         */
        public boolean hasResult() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string result = 1;</code>
         */
        public java.lang.String getResult() {
          java.lang.Object ref = result_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            result_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string result = 1;</code>
         */
        public com.google.protobuf.ByteString
            getResultBytes() {
          java.lang.Object ref = result_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            result_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder setResult(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder clearResult() {
          bitField0_ = (bitField0_ & ~0x00000001);
          result_ = getDefaultInstance().getResult();
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder setResultBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          result_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ServerProc.SUser)
      }

      static {
        defaultInstance = new SUser(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ServerProc.SUser)
    }

    public interface SChatInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string result = 1;
      /**
       * <code>required string result = 1;</code>
       */
      boolean hasResult();
      /**
       * <code>required string result = 1;</code>
       */
      java.lang.String getResult();
      /**
       * <code>required string result = 1;</code>
       */
      com.google.protobuf.ByteString
          getResultBytes();

      // required string type = 2;
      /**
       * <code>required string type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 2;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 2;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      // required string words = 3;
      /**
       * <code>required string words = 3;</code>
       */
      boolean hasWords();
      /**
       * <code>required string words = 3;</code>
       */
      java.lang.String getWords();
      /**
       * <code>required string words = 3;</code>
       */
      com.google.protobuf.ByteString
          getWordsBytes();
    }
    /**
     * Protobuf type {@code ServerProc.SChatInfo}
     */
    public static final class SChatInfo extends
        com.google.protobuf.GeneratedMessage
        implements SChatInfoOrBuilder {
      // Use SChatInfo.newBuilder() to construct.
      private SChatInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SChatInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SChatInfo defaultInstance;
      public static SChatInfo getDefaultInstance() {
        return defaultInstance;
      }

      public SChatInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SChatInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                result_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                type_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                words_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SChatInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SChatInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.class, com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<SChatInfo> PARSER =
          new com.google.protobuf.AbstractParser<SChatInfo>() {
        public SChatInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SChatInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SChatInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string result = 1;
      public static final int RESULT_FIELD_NUMBER = 1;
      private java.lang.Object result_;
      /**
       * <code>required string result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private java.lang.Object type_;
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string words = 3;
      public static final int WORDS_FIELD_NUMBER = 3;
      private java.lang.Object words_;
      /**
       * <code>required string words = 3;</code>
       */
      public boolean hasWords() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string words = 3;</code>
       */
      public java.lang.String getWords() {
        java.lang.Object ref = words_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            words_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string words = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWordsBytes() {
        java.lang.Object ref = words_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          words_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        result_ = "";
        type_ = "";
        words_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasResult()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWords()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getResultBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getWordsBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getResultBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getWordsBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.bean.ServerInformationPacket.ServerProc.SChatInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ServerProc.SChatInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SChatInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SChatInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.class, com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder.class);
        }

        // Construct using com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          result_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          words_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.bean.ServerInformationPacket.internal_static_ServerProc_SChatInfo_descriptor;
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo getDefaultInstanceForType() {
          return com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance();
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo build() {
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo buildPartial() {
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo result = new com.server.bean.ServerInformationPacket.ServerProc.SChatInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.result_ = result_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.words_ = words_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.bean.ServerInformationPacket.ServerProc.SChatInfo) {
            return mergeFrom((com.server.bean.ServerInformationPacket.ServerProc.SChatInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.bean.ServerInformationPacket.ServerProc.SChatInfo other) {
          if (other == com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance()) return this;
          if (other.hasResult()) {
            bitField0_ |= 0x00000001;
            result_ = other.result_;
            onChanged();
          }
          if (other.hasType()) {
            bitField0_ |= 0x00000002;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasWords()) {
            bitField0_ |= 0x00000004;
            words_ = other.words_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResult()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          if (!hasWords()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.bean.ServerInformationPacket.ServerProc.SChatInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string result = 1;
        private java.lang.Object result_ = "";
        /**
         * <code>required string result = 1;</code>
         */
        public boolean hasResult() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string result = 1;</code>
         */
        public java.lang.String getResult() {
          java.lang.Object ref = result_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            result_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string result = 1;</code>
         */
        public com.google.protobuf.ByteString
            getResultBytes() {
          java.lang.Object ref = result_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            result_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder setResult(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder clearResult() {
          bitField0_ = (bitField0_ & ~0x00000001);
          result_ = getDefaultInstance().getResult();
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 1;</code>
         */
        public Builder setResultBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          result_ = value;
          onChanged();
          return this;
        }

        // required string type = 2;
        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string type = 2;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }

        // required string words = 3;
        private java.lang.Object words_ = "";
        /**
         * <code>required string words = 3;</code>
         */
        public boolean hasWords() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string words = 3;</code>
         */
        public java.lang.String getWords() {
          java.lang.Object ref = words_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            words_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string words = 3;</code>
         */
        public com.google.protobuf.ByteString
            getWordsBytes() {
          java.lang.Object ref = words_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            words_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string words = 3;</code>
         */
        public Builder setWords(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          words_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string words = 3;</code>
         */
        public Builder clearWords() {
          bitField0_ = (bitField0_ & ~0x00000004);
          words_ = getDefaultInstance().getWords();
          onChanged();
          return this;
        }
        /**
         * <code>required string words = 3;</code>
         */
        public Builder setWordsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          words_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ServerProc.SChatInfo)
      }

      static {
        defaultInstance = new SChatInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ServerProc.SChatInfo)
    }

    private int bitField0_;
    // optional .ServerProc.SUser user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private com.server.bean.ServerInformationPacket.ServerProc.SUser user_;
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    public com.server.bean.ServerInformationPacket.ServerProc.SUser getUser() {
      return user_;
    }
    /**
     * <code>optional .ServerProc.SUser user = 1;</code>
     */
    public com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder getUserOrBuilder() {
      return user_;
    }

    // optional .ServerProc.SChatInfo chatInfo = 2;
    public static final int CHATINFO_FIELD_NUMBER = 2;
    private com.server.bean.ServerInformationPacket.ServerProc.SChatInfo chatInfo_;
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    public boolean hasChatInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo getChatInfo() {
      return chatInfo_;
    }
    /**
     * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
     */
    public com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder getChatInfoOrBuilder() {
      return chatInfo_;
    }

    private void initFields() {
      user_ = com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance();
      chatInfo_ = com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasUser()) {
        if (!getUser().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasChatInfo()) {
        if (!getChatInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, chatInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chatInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.bean.ServerInformationPacket.ServerProc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.bean.ServerInformationPacket.ServerProc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerProc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.bean.ServerInformationPacket.ServerProcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.bean.ServerInformationPacket.ServerProc.class, com.server.bean.ServerInformationPacket.ServerProc.Builder.class);
      }

      // Construct using com.server.bean.ServerInformationPacket.ServerProc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
          getChatInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chatInfoBuilder_ == null) {
          chatInfo_ = com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance();
        } else {
          chatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.bean.ServerInformationPacket.internal_static_ServerProc_descriptor;
      }

      public com.server.bean.ServerInformationPacket.ServerProc getDefaultInstanceForType() {
        return com.server.bean.ServerInformationPacket.ServerProc.getDefaultInstance();
      }

      public com.server.bean.ServerInformationPacket.ServerProc build() {
        com.server.bean.ServerInformationPacket.ServerProc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.bean.ServerInformationPacket.ServerProc buildPartial() {
        com.server.bean.ServerInformationPacket.ServerProc result = new com.server.bean.ServerInformationPacket.ServerProc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (chatInfoBuilder_ == null) {
          result.chatInfo_ = chatInfo_;
        } else {
          result.chatInfo_ = chatInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.bean.ServerInformationPacket.ServerProc) {
          return mergeFrom((com.server.bean.ServerInformationPacket.ServerProc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.bean.ServerInformationPacket.ServerProc other) {
        if (other == com.server.bean.ServerInformationPacket.ServerProc.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasChatInfo()) {
          mergeChatInfo(other.getChatInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasUser()) {
          if (!getUser().isInitialized()) {
            
            return false;
          }
        }
        if (hasChatInfo()) {
          if (!getChatInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.bean.ServerInformationPacket.ServerProc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.bean.ServerInformationPacket.ServerProc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ServerProc.SUser user = 1;
      private com.server.bean.ServerInformationPacket.ServerProc.SUser user_ = com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ServerInformationPacket.ServerProc.SUser, com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder, com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder> userBuilder_;
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SUser getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public Builder setUser(com.server.bean.ServerInformationPacket.ServerProc.SUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public Builder setUser(
          com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public Builder mergeUser(com.server.bean.ServerInformationPacket.ServerProc.SUser value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              user_ != com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance()) {
            user_ =
              com.server.bean.ServerInformationPacket.ServerProc.SUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.server.bean.ServerInformationPacket.ServerProc.SUser.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder getUserBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      /**
       * <code>optional .ServerProc.SUser user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ServerInformationPacket.ServerProc.SUser, com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder, com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.bean.ServerInformationPacket.ServerProc.SUser, com.server.bean.ServerInformationPacket.ServerProc.SUser.Builder, com.server.bean.ServerInformationPacket.ServerProc.SUserOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // optional .ServerProc.SChatInfo chatInfo = 2;
      private com.server.bean.ServerInformationPacket.ServerProc.SChatInfo chatInfo_ = com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo, com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder, com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder> chatInfoBuilder_;
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public boolean hasChatInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo getChatInfo() {
        if (chatInfoBuilder_ == null) {
          return chatInfo_;
        } else {
          return chatInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public Builder setChatInfo(com.server.bean.ServerInformationPacket.ServerProc.SChatInfo value) {
        if (chatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatInfo_ = value;
          onChanged();
        } else {
          chatInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public Builder setChatInfo(
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder builderForValue) {
        if (chatInfoBuilder_ == null) {
          chatInfo_ = builderForValue.build();
          onChanged();
        } else {
          chatInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public Builder mergeChatInfo(com.server.bean.ServerInformationPacket.ServerProc.SChatInfo value) {
        if (chatInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              chatInfo_ != com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance()) {
            chatInfo_ =
              com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.newBuilder(chatInfo_).mergeFrom(value).buildPartial();
          } else {
            chatInfo_ = value;
          }
          onChanged();
        } else {
          chatInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public Builder clearChatInfo() {
        if (chatInfoBuilder_ == null) {
          chatInfo_ = com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.getDefaultInstance();
          onChanged();
        } else {
          chatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder getChatInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getChatInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      public com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder getChatInfoOrBuilder() {
        if (chatInfoBuilder_ != null) {
          return chatInfoBuilder_.getMessageOrBuilder();
        } else {
          return chatInfo_;
        }
      }
      /**
       * <code>optional .ServerProc.SChatInfo chatInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.bean.ServerInformationPacket.ServerProc.SChatInfo, com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder, com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder> 
          getChatInfoFieldBuilder() {
        if (chatInfoBuilder_ == null) {
          chatInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.bean.ServerInformationPacket.ServerProc.SChatInfo, com.server.bean.ServerInformationPacket.ServerProc.SChatInfo.Builder, com.server.bean.ServerInformationPacket.ServerProc.SChatInfoOrBuilder>(
                  chatInfo_,
                  getParentForChildren(),
                  isClean());
          chatInfo_ = null;
        }
        return chatInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ServerProc)
    }

    static {
      defaultInstance = new ServerProc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerProc)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerProc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerProc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerProc_SUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerProc_SUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerProc_SChatInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerProc_SChatInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\"\251\001\n\nServerProc\022\037\n\004user\030\001 " +
      "\001(\0132\021.ServerProc.SUser\022\'\n\010chatInfo\030\002 \001(\013" +
      "2\025.ServerProc.SChatInfo\032\027\n\005SUser\022\016\n\006resu" +
      "lt\030\001 \002(\t\0328\n\tSChatInfo\022\016\n\006result\030\001 \002(\t\022\014\n" +
      "\004type\030\002 \002(\t\022\r\n\005words\030\003 \002(\tB*\n\017com.server" +
      ".beanB\027ServerInformationPacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ServerProc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ServerProc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerProc_descriptor,
              new java.lang.String[] { "User", "ChatInfo", });
          internal_static_ServerProc_SUser_descriptor =
            internal_static_ServerProc_descriptor.getNestedTypes().get(0);
          internal_static_ServerProc_SUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerProc_SUser_descriptor,
              new java.lang.String[] { "Result", });
          internal_static_ServerProc_SChatInfo_descriptor =
            internal_static_ServerProc_descriptor.getNestedTypes().get(1);
          internal_static_ServerProc_SChatInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerProc_SChatInfo_descriptor,
              new java.lang.String[] { "Result", "Type", "Words", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
